/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ssanalytics.snapshotplugin.ui.generator.profile;

/**
 *
 * @author christian
 */
public class PhotoGraphPanel extends javax.swing.JPanel {

    /**
     * Creates new form PhotoGraphPanel
     */
    public PhotoGraphPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        cbShowFriends = new javax.swing.JCheckBox();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.BorderLayout());

        org.openide.awt.Mnemonics.setLocalizedText(cbShowFriends, org.openide.util.NbBundle.getMessage(PhotoGraphPanel.class, "PhotoGraphPanel.cbShowFriends.text")); // NOI18N
        cbShowFriends.setName("cbShowFriends"); // NOI18N
        mainPanel.add(cbShowFriends, java.awt.BorderLayout.CENTER);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbShowFriends;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    public boolean getShowFriends() {
        return cbShowFriends.isSelected();
    }
    
    public void setShowFriends(boolean friendsVisible) {
        cbShowFriends.setSelected(friendsVisible);
    }
}
