/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ssanalytics.snapshotplugin.ui.jsonSnapshotInsert;

import java.awt.BorderLayout;
import javax.swing.JLabel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.ssanalytics.snapshotplugin.config.dynamicConfig.ConfigurationFileManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd = "-//org.ssanalytics.snapshotplugin.ui.jsonSnapshotInsert//SnapshotInsert//EN",
autostore = false)
@TopComponent.Description(
    preferredID = "SnapshotInsertTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "graphmode", openAtStartup = false)
@ActionID(category = "Window", id = "org.ssanalytics.snapshotplugin.ui.jsonSnapshotInsert.SnapshotInsertTopComponent")
@ActionReference(path = "Menu/Plugins/Snapshot Plugin" , position = 100)
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_SnapshotInsertAction",
preferredID = "SnapshotInsertTopComponent")
public final class SnapshotInsertTopComponent extends TopComponent {

    public SnapshotInsertTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(SnapshotInsertTopComponent.class, "CTL_SnapshotInsertTopComponent"));

        if(ConfigurationFileManager.getCurrentConfig() != null) {
        mainPanel.add(new SnapshotInsertPanel(), BorderLayout.CENTER);
        }
        else {
            mainPanel.add(new JLabel("Configuration File not found!"), BorderLayout.CENTER);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        mainPanel.setLayout(new java.awt.BorderLayout());
        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
