/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ssanalytics.snapshotplugin.ui.generator.snapshot;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import org.gephi.lib.validation.BetweenZeroAndOneValidator;
import org.gephi.lib.validation.PositiveNumberValidator;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.netbeans.validation.api.ui.ValidationPanel;

/**
 *
 * @author christian
 */
public class EvidenceCountGraphPanel extends javax.swing.JPanel {

    private DefaultListModel<String> model;

    /**
     * Creates new form EvidenceCountGraphPanel
     */
    //List<String> categories
    public EvidenceCountGraphPanel(List<String> categories) {
        model = new DefaultListModel<>();
        for(String s : categories)
            model.addElement(s);
        initComponents();
    }

    public static ValidationPanel createValidationPanel(EvidenceCountGraphPanel innerPanel, List<String> categories) {
        ValidationPanel validationPanel = new ValidationPanel();
        if (innerPanel == null) {
            innerPanel = new EvidenceCountGraphPanel(categories);
        }
        validationPanel.setInnerComponent(innerPanel);

        return validationPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCategories = new javax.swing.JList();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listCategories.setModel(model);
        listCategories.setName("listCategories"); // NOI18N
        jScrollPane1.setViewportView(listCategories);

        mainPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JList listCategories;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
